### ISSUE TITLE
Aeon Labs' Z-Stick Gen5

### ISSUE THREAD

**Issue by anton-johansson** [whizzosoftware/WZWave#15]
In your list of [supported devices](https://whizzosoftware.atlassian.net/wiki/spaces/WZWAV/pages/1540100/Device+Support) I can see "Aeon Labs' Z-Stick 2". I really want to get into the Z-Wave business, and this library seems really appealing to me. I don't have any devices yet, I'm just gathering information. I was thinking of buying the "Aeon Labs' Z-Stick Gen5". Do you have any clue if that works out of the box with WZWave?

In the future, I'll gladly help testing out devices and contribute, but to get started I'd like to use a controller that supposedely works out of the box. :)

**Comment by whizzosoftware** [comment]
I do have an Aeon Labs Z-Stick Gen5 that I tried with WZWave but I can't say that it works perfectly -- I saw some strange errors in the log that I didn't make sense at first glance. Part of the issue here is that Sigma Designs has not released documentation for the serial protocol used to communicate with the controller (last I checked, they had only released the command protocol documentation). I was able to implement the serial protocol portions of WZWave using what information was found floating around the Internet in various forms (blogs, web pages, open source projects, etc.). I couldn't tell if the errors I saw were somehow related to ZWave Plus or some other aspect of the serial protocol that I don't fully understand. Fortunately, WZWave is set up to be very easily unit-testable and it should be quite easy to add unit tests that replicate the Gen5 serial data that is causing problems. Figuring out how to fix it is another story though and would require some time and effort. So, to summarize, Z-Stick 2 should work pretty reliably and Z-Stick Gen5 will require some development work to support. I'd certainly be up for collaborating if it's something you are interested in working on.

**Comment by anton-johansson** [comment]
Allright, thanks for the summary. I actually ordered a Gen5 stick yesterday, I should be getting it today. I could mess around a bit with it and see if I find anything. It might be a bit over my head, we'll see.

**Comment by Ziver** [comment]
I've been trying to get WZWave to work with Z-Stick Gen5 without any success, so I'm open for helping out.

**Comment by anton-johansson** [comment]
I got my gear today, and I managed to connect to my Z-Stick Gen5. I haven't tested it with any other devices yet, I got hold up with the architecture of my application, but I'll mess around with it as soon as I have the time. But the fact that I could connect to it sounds good atleaast. :)

**Comment by anton-johansson** [comment]
As described in issue #18, I'm using the Z-Stick Gen5 together with a power on/off & meter-switch. I think it's safe to say that the Z-Stick Gen5 works with WZWave. :)
